import { Theme } from './interfaces';
import {
    matCoreTheme,
    matAutocompleteTheme,
    matButtonTheme,
    matButtonToggleTheme,
    matCardTheme,
    matCheckboxTheme,
    matChipsTheme,
    matTableTheme,
    matDatepickerTheme,
    matDialogTheme,
    matDividerTheme,
    matExpansionPanelTheme,
    matFormFieldTheme,
    matGridListTheme,
    matIconTheme,
    matInputTheme,
    matListTheme,
    matMenuTheme,
    matPaginatorTheme,
    matProgressBarTheme,
    matProgressSpinnerTheme,
    matRadioTheme,
    matSelectTheme,
    matSidenavTheme,
    matSlideToggleTheme,
    matSliderTheme,
    matStepperTheme,
    matTabsTheme,
    matToolbarTheme,
    matTooltipTheme,
    matSnackBarTheme
} from './theme';

// Create a theme.
export function angularMaterialTheme(theme: Theme): Object {
    return {
        ...matCoreTheme(theme),
        ...matAutocompleteTheme(theme),
        ...matButtonTheme(theme),
        ...matButtonToggleTheme(theme),
        ...matCardTheme(theme),
        ...matCheckboxTheme(theme),
        ...matChipsTheme(theme),
        ...matTableTheme(theme),
        ...matDatepickerTheme(theme),
        ...matDialogTheme(theme),
        ...matDividerTheme(theme),
        ...matExpansionPanelTheme(theme),
        ...matFormFieldTheme(theme),
        ...matGridListTheme(theme),
        ...matIconTheme(theme),
        ...matInputTheme(theme),
        ...matListTheme(theme),
        ...matMenuTheme(theme),
        ...matPaginatorTheme(theme),
        ...matProgressBarTheme(theme),
        ...matProgressSpinnerTheme(theme),
        ...matRadioTheme(theme),
        ...matSelectTheme(theme),
        ...matSidenavTheme(theme),
        ...matSlideToggleTheme(theme),
        ...matSliderTheme(theme),
        ...matStepperTheme(theme),
        ...matTabsTheme(theme),
        ...matToolbarTheme(theme),
        ...matTooltipTheme(theme),
        ...matSnackBarTheme(theme)
    };
}
